#!/usr/bin/env python3
"""Seed the prospects database with lookalike companies."""

import sqlite3
from datetime import datetime

DB_PATH = "/Users/kylelangford/ai-context/tools/prospect-finder/db/prospects.db"

# Prospect data from lookalike analysis
PROSPECTS = [
    # Tier 1: Healthcare / Insurance
    {
        "name": "Health Care Service Corporation (HCSC)",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 60000,
        "geography": "National",
        "headquarters": "Chicago, IL",
        "similar_to": "BlueCross BlueShield",
        "match_tier": 1,
        "match_reason": "Largest customer-owned health insurer (BCBS IL, TX, MT, OK, NM). Just acquired Cigna Medicare. Complex multi-state, member engagement needs.",
        "fit_score": 90,
        "budget_estimate": "enterprise",
        "budget_low": 500000,
        "budget_high": 2000000,
        "signal_type": "acquisition",
        "signal_detail": "Acquired Cigna Medicare business March 2025, rebranding to HealthSpring",
        "tags": "bcbs,medicare,acquisition,high-priority"
    },
    {
        "name": "Elevance Health (Anthem BCBS)",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 100000,
        "geography": "National",
        "headquarters": "Indianapolis, IN",
        "similar_to": "United Healthcare",
        "match_tier": 1,
        "match_reason": "14-state BCBS affiliate. Medicare + commercial. Digital transformation underway. National reach, regional identity.",
        "fit_score": 88,
        "budget_estimate": "enterprise",
        "budget_low": 500000,
        "budget_high": 2000000,
        "tags": "bcbs,fortune-500,digital-transformation"
    },
    {
        "name": "Centene Corporation",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 74000,
        "geography": "National",
        "headquarters": "St. Louis, MO",
        "similar_to": "Humana",
        "match_tier": 1,
        "match_reason": "Medicaid/Medicare focused. 28M+ members. Heavy content/education needs for underserved populations.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 400000,
        "budget_high": 1500000,
        "tags": "medicaid,medicare,underserved"
    },
    {
        "name": "Molina Healthcare",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 16000,
        "geography": "National",
        "headquarters": "Long Beach, CA",
        "similar_to": "Humana",
        "match_tier": 1,
        "match_reason": "Medicaid specialist. $36B revenue. Growing Medicare Advantage. Underserved population focus.",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 1000000,
        "tags": "medicaid,medicare,growth"
    },
    {
        "name": "Point32Health",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "5000-10000",
        "employee_count": 5000,
        "geography": "Regional",
        "headquarters": "Canton, MA",
        "similar_to": "BlueCross BlueShield, Vicinity",
        "match_tier": 1,
        "match_reason": "Harvard Pilgrim + Tufts merger. New England regional. Brand integration needs. 2M+ members.",
        "fit_score": 92,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 600000,
        "signal_type": "merger",
        "signal_detail": "Recent merger creating brand integration opportunity",
        "tags": "new-england,merger,brand-integration,hot-prospect"
    },
    {
        "name": "Independence Blue Cross",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "5000-10000",
        "employee_count": 10000,
        "geography": "Regional",
        "headquarters": "Philadelphia, PA",
        "similar_to": "BlueCross BlueShield",
        "match_tier": 1,
        "match_reason": "Philadelphia region. 9M members. Digital member experience investment.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 800000,
        "tags": "bcbs,regional,digital-experience"
    },
    {
        "name": "Highmark Health",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 46000,
        "geography": "Regional",
        "headquarters": "Pittsburgh, PA",
        "similar_to": "BlueCross BlueShield, Optum",
        "match_tier": 1,
        "match_reason": "PA/WV/DE BCBS. Health system + insurance integrated. Complex stakeholder marketing.",
        "fit_score": 83,
        "budget_estimate": "enterprise",
        "budget_low": 400000,
        "budget_high": 1200000,
        "tags": "bcbs,integrated-delivery,complex"
    },
    {
        "name": "CareFirst BCBS",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "5000-10000",
        "employee_count": 6000,
        "geography": "Regional",
        "headquarters": "Baltimore, MD",
        "similar_to": "BlueCross BlueShield",
        "match_tier": 1,
        "match_reason": "DC/MD/VA region. 3.5M members. Community health focus.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "bcbs,regional,dc-metro"
    },
    {
        "name": "Premera Blue Cross",
        "industry": "Healthcare / Insurance",
        "segment": "healthcare",
        "org_type": "Enterprise",
        "size_range": "2000-5000",
        "employee_count": 3500,
        "geography": "Regional",
        "headquarters": "Mountlake Terrace, WA",
        "similar_to": "BlueCross BlueShield",
        "match_tier": 1,
        "match_reason": "Pacific Northwest. 2M+ members. Alaska/Washington focus.",
        "fit_score": 75,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "bcbs,regional,pacific-northwest"
    },

    # Tier 1: Digital Health
    {
        "name": "Assort Health",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Startup",
        "size_range": "50-200",
        "geography": "National",
        "headquarters": "California",
        "similar_to": "Lightfully Health, PopHealth",
        "match_tier": 1,
        "match_reason": "$76M Series B (Oct 2025). AI patient engagement platform. High growth, complex UX needs.",
        "fit_score": 88,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "funding_stage": "Series B",
        "funding_amount": "$76M",
        "signal_type": "funding",
        "signal_detail": "$76M Series B October 2025, led by Lightspeed",
        "tags": "ai,patient-engagement,series-b,hot-prospect"
    },
    {
        "name": "Healthie",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Startup",
        "size_range": "50-200",
        "geography": "National",
        "headquarters": "New York, NY",
        "similar_to": "Linkwell Health",
        "match_tier": 1,
        "match_reason": "$23M Series B. EHR + patient engagement for virtual-first care. API-first platform.",
        "fit_score": 82,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "funding_stage": "Series B",
        "funding_amount": "$23M",
        "signal_type": "funding",
        "signal_detail": "$23M Series B October 2024",
        "tags": "ehr,virtual-care,api,series-b"
    },
    {
        "name": "Courier Health",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Startup",
        "size_range": "50-200",
        "geography": "National",
        "similar_to": "Linkwell Health, HealthInsurance.com",
        "match_tier": 1,
        "match_reason": "$50M Series B. Biopharma patient journey platform. Complex user flows.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "funding_stage": "Series B",
        "funding_amount": "$50M",
        "signal_type": "funding",
        "tags": "biopharma,patient-journey,series-b"
    },
    {
        "name": "Tebra",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Growth Stage",
        "size_range": "500-1000",
        "geography": "National",
        "headquarters": "California",
        "similar_to": "HealthInsurance.com",
        "match_tier": 1,
        "match_reason": "$245M funding (Kareo + PatientPop merger). Practice management + marketing for providers. SMB healthcare focus.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "funding_amount": "$245M",
        "signal_type": "merger",
        "tags": "practice-management,smb,merger"
    },
    {
        "name": "Wheel",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Growth Stage",
        "size_range": "200-500",
        "geography": "National",
        "similar_to": "Optum, Linkwell Health",
        "match_tier": 1,
        "match_reason": "$216M raised. B2B telehealth infrastructure. Health plan partnerships.",
        "fit_score": 77,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 350000,
        "funding_amount": "$216M",
        "tags": "telehealth,b2b,infrastructure"
    },
    {
        "name": "Headway",
        "industry": "Digital Health / Mental Health",
        "segment": "digital-health",
        "org_type": "Growth Stage",
        "size_range": "500-1000",
        "geography": "National",
        "similar_to": "Lightfully Health",
        "match_tier": 1,
        "match_reason": "$400M+ raised. Mental health provider network. Payer partnerships.",
        "fit_score": 85,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 500000,
        "funding_amount": "$400M+",
        "tags": "mental-health,provider-network,high-growth"
    },
    {
        "name": "Spring Health",
        "industry": "Digital Health / Mental Health",
        "segment": "digital-health",
        "org_type": "Growth Stage",
        "size_range": "500-1000",
        "geography": "National",
        "similar_to": "Lightfully Health, Linkwell Health",
        "match_tier": 1,
        "match_reason": "$300M+ raised. Employer mental health platform. B2B2C marketing.",
        "fit_score": 83,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 450000,
        "funding_amount": "$300M+",
        "tags": "mental-health,employer,b2b2c"
    },
    {
        "name": "Cityblock Health",
        "industry": "Digital Health",
        "segment": "digital-health",
        "org_type": "Growth Stage",
        "size_range": "1000-2000",
        "geography": "National",
        "similar_to": "Humana, PopHealth",
        "match_tier": 1,
        "match_reason": "Value-based care for Medicaid populations. Complex member engagement.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "medicaid,value-based-care,underserved"
    },

    # Tier 1: Higher Education
    {
        "name": "Brown University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "2000-5000",
        "employee_count": 4600,
        "geography": "National",
        "headquarters": "Providence, RI",
        "similar_to": "Dartmouth",
        "match_tier": 1,
        "match_reason": "Ivy League. Alumni magazine. Similar stakeholder complexity to Dartmouth.",
        "fit_score": 90,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "ivy-league,alumni-magazine,new-england"
    },
    {
        "name": "Yale University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 14000,
        "geography": "National",
        "headquarters": "New Haven, CT",
        "similar_to": "Columbia",
        "match_tier": 1,
        "match_reason": "Ivy League. Multi-school structure. Digital ecosystem complexity.",
        "fit_score": 88,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 800000,
        "tags": "ivy-league,multi-school,complex"
    },
    {
        "name": "Cornell University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 18000,
        "geography": "National",
        "headquarters": "Ithaca, NY",
        "similar_to": "Columbia, Penn State",
        "match_tier": 1,
        "match_reason": "Ivy League. Land-grant hybrid. Large alumni network.",
        "fit_score": 87,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "ivy-league,land-grant,large-alumni"
    },
    {
        "name": "University of Virginia",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 12000,
        "geography": "National",
        "headquarters": "Charlottesville, VA",
        "similar_to": "Penn State",
        "match_tier": 1,
        "match_reason": "Public Ivy. Strong alumni engagement. Digital transformation.",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "public-ivy,alumni,digital-transformation"
    },
    {
        "name": "University of Michigan",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 50000,
        "geography": "National",
        "headquarters": "Ann Arbor, MI",
        "similar_to": "Penn State",
        "match_tier": 1,
        "match_reason": "Large public R1. Multi-campus. Alumni magazine. Athletic brand.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "r1,public,athletics,alumni-magazine"
    },
    {
        "name": "Northwestern University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "5000-10000",
        "employee_count": 8000,
        "geography": "National",
        "headquarters": "Evanston, IL",
        "similar_to": "Columbia",
        "match_tier": 1,
        "match_reason": "Top research university. Alumni magazine (Northwestern Magazine). Chicago market.",
        "fit_score": 86,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "tags": "research,alumni-magazine,chicago"
    },
    {
        "name": "Duke University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 40000,
        "geography": "National",
        "headquarters": "Durham, NC",
        "similar_to": "Dartmouth, Healthcare clients",
        "match_tier": 1,
        "match_reason": "Elite research university. Alumni magazine. Healthcare integration (Duke Health).",
        "fit_score": 88,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "research,alumni-magazine,healthcare-integration"
    },
    {
        "name": "Emory University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "10000+",
        "employee_count": 33000,
        "geography": "National",
        "headquarters": "Atlanta, GA",
        "similar_to": "Columbia",
        "match_tier": 1,
        "match_reason": "Research university. CDC adjacency. Health focus. Atlanta market.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "research,cdc,health-focus"
    },
    {
        "name": "Georgetown University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "5000-10000",
        "employee_count": 6000,
        "geography": "National",
        "headquarters": "Washington, DC",
        "similar_to": "Princeton",
        "match_tier": 1,
        "match_reason": "Elite private. DC market. Alumni magazine. Policy orientation.",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "elite,dc,policy,alumni-magazine"
    },
    {
        "name": "Wellesley College",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "Liberal Arts College",
        "size_range": "500-1000",
        "employee_count": 1000,
        "geography": "National",
        "headquarters": "Wellesley, MA",
        "similar_to": "Dartmouth",
        "match_tier": 1,
        "match_reason": "Elite liberal arts. Alumni engagement. Women's college positioning.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "tags": "liberal-arts,elite,womens-college,new-england"
    },
    {
        "name": "Williams College",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "Liberal Arts College",
        "size_range": "500-1000",
        "employee_count": 1200,
        "geography": "National",
        "headquarters": "Williamstown, MA",
        "similar_to": "Dartmouth",
        "match_tier": 1,
        "match_reason": "Top liberal arts. Alumni magazine. New England.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "tags": "liberal-arts,elite,new-england"
    },
    {
        "name": "Amherst College",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "Liberal Arts College",
        "size_range": "500-1000",
        "employee_count": 900,
        "geography": "National",
        "headquarters": "Amherst, MA",
        "similar_to": "Dartmouth",
        "match_tier": 1,
        "match_reason": "Top liberal arts. Consortium member. Alumni focus.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 250000,
        "tags": "liberal-arts,elite,consortium,new-england"
    },
    {
        "name": "Middlebury College",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "Liberal Arts College",
        "size_range": "500-1000",
        "employee_count": 1300,
        "geography": "National",
        "headquarters": "Middlebury, VT",
        "similar_to": "Dartmouth",
        "match_tier": 1,
        "match_reason": "Elite liberal arts. Vermont. Environmental positioning.",
        "fit_score": 77,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 250000,
        "tags": "liberal-arts,elite,environmental,new-england"
    },
    {
        "name": "Boston College",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "5000-10000",
        "employee_count": 6000,
        "geography": "National",
        "headquarters": "Chestnut Hill, MA",
        "similar_to": "Penn State",
        "match_tier": 1,
        "match_reason": "Large Catholic university. Strong alumni. Boston market.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "catholic,alumni,boston,athletics"
    },
    {
        "name": "Tufts University",
        "industry": "Higher Education",
        "segment": "higher-ed",
        "org_type": "University",
        "size_range": "5000-10000",
        "employee_count": 5500,
        "geography": "National",
        "headquarters": "Medford, MA",
        "similar_to": "Columbia",
        "match_tier": 1,
        "match_reason": "Research university. Boston. Multi-school (Dental, Fletcher, etc.).",
        "fit_score": 82,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "research,multi-school,boston"
    },

    # Tier 1: Publishing / Media
    {
        "name": "Outside Inc.",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Publisher",
        "size_range": "200-500",
        "geography": "National",
        "headquarters": "Boulder, CO",
        "similar_to": "Rodale Publishing",
        "match_tier": 1,
        "match_reason": "Yoga Journal, Backpacker, Climbing, SKI, Women's Running. Enthusiast portfolio. Print-to-digital.",
        "fit_score": 90,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "signal_type": "acquisition",
        "signal_detail": "Acquired Active Interest Media titles, portfolio consolidation",
        "tags": "enthusiast,multi-title,outdoor,wellness,hot-prospect"
    },
    {
        "name": "Outdoor Sportsman Group",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Publisher",
        "size_range": "200-500",
        "geography": "National",
        "similar_to": "Rodale, Runner's World",
        "match_tier": 1,
        "match_reason": "28 regional + 14 national hunting/fishing titles. Enthusiast media empire.",
        "fit_score": 82,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 350000,
        "tags": "enthusiast,hunting-fishing,regional,outdoor"
    },
    {
        "name": "Meredith/Dotdash",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Enterprise Publisher",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "New York, NY",
        "similar_to": "Condé Nast",
        "match_tier": 1,
        "match_reason": "Better Homes, People, Real Simple. Now IAC-owned. Health + lifestyle portfolio.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 800000,
        "tags": "multi-title,lifestyle,iac,large"
    },
    {
        "name": "Bonnier Corp",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Publisher",
        "size_range": "200-500",
        "geography": "National",
        "similar_to": "Bicycling, Organic Gardening",
        "match_tier": 1,
        "match_reason": "Boating, sailing, outdoor titles (Popular Science, Field & Stream sold). Enthusiast focus.",
        "fit_score": 75,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "tags": "boating,outdoor,enthusiast"
    },
    {
        "name": "Future PLC",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Enterprise Publisher",
        "size_range": "2000-5000",
        "geography": "Global",
        "headquarters": "London, UK (US offices)",
        "similar_to": "Men's Health",
        "match_tier": 1,
        "match_reason": "Guitar World, Tom's Hardware, GamesRadar. UK-based, US growing. Enthusiast digital.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "enthusiast,digital,uk,tech-lifestyle"
    },
    {
        "name": "Penske Media",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Enterprise Publisher",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "Los Angeles, CA",
        "similar_to": "Condé Nast",
        "match_tier": 1,
        "match_reason": "Rolling Stone, Variety, WWD. Digital transformation. Luxury/culture.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "tags": "entertainment,culture,luxury,digital"
    },
    {
        "name": "Bustle Digital Group",
        "industry": "Media / Publishing",
        "segment": "publishing",
        "org_type": "Digital Publisher",
        "size_range": "200-500",
        "geography": "National",
        "headquarters": "New York, NY",
        "similar_to": "Women's Health, SELF",
        "match_tier": 1,
        "match_reason": "Bustle, Elite Daily, Scary Mommy. Women's digital. Millennial focus.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "tags": "digital-native,women,millennial"
    },

    # Tier 2: EdTech
    {
        "name": "SchooLinks",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "SaaS",
        "size_range": "100-200",
        "geography": "National",
        "similar_to": "Lexia, Gray",
        "match_tier": 2,
        "match_reason": "$80M Series B. College/career readiness K-12. B2B (school districts).",
        "fit_score": 85,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "funding_stage": "Series B",
        "funding_amount": "$80M",
        "signal_type": "funding",
        "tags": "k12,college-career,series-b,growth"
    },
    {
        "name": "Newsela",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "SaaS",
        "size_range": "200-500",
        "geography": "National",
        "similar_to": "Lexia",
        "match_tier": 2,
        "match_reason": "$200M+ raised. K-12 instructional content. Literacy focus.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 350000,
        "funding_amount": "$200M+",
        "tags": "k12,content,literacy"
    },
    {
        "name": "Renaissance Learning",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "Wisconsin Rapids, WI",
        "similar_to": "Lexia",
        "match_tier": 2,
        "match_reason": "$1B+ revenue. Assessment + learning. PE-backed (Francisco Partners).",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "assessment,pe-backed,large"
    },
    {
        "name": "Curriculum Associates",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "North Billerica, MA",
        "similar_to": "Lexia",
        "match_tier": 2,
        "match_reason": "i-Ready platform. K-12 assessment. Boston-area.",
        "fit_score": 83,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "assessment,boston,k12"
    },
    {
        "name": "PowerSchool",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "Folsom, CA",
        "similar_to": "Lexia, Gray",
        "match_tier": 2,
        "match_reason": "$700M+ revenue. Student information systems. K-12 infrastructure.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "tags": "sis,infrastructure,large"
    },
    {
        "name": "Ellucian",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "Reston, VA",
        "similar_to": "Gray Decision Intelligence",
        "match_tier": 2,
        "match_reason": "Higher ed ERP/SIS. PE-backed. Large installed base.",
        "fit_score": 78,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "tags": "higher-ed,erp,pe-backed"
    },
    {
        "name": "Instructure (Canvas)",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "Salt Lake City, UT",
        "similar_to": "Lexia",
        "match_tier": 2,
        "match_reason": "LMS market leader. Higher ed + K-12. PE-backed (Thoma Bravo).",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "lms,pe-backed,higher-ed,k12"
    },
    {
        "name": "Anthology (Blackboard)",
        "industry": "EdTech",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "Boca Raton, FL",
        "similar_to": "Gray, Lexia",
        "match_tier": 2,
        "match_reason": "Higher ed technology suite. Complex enterprise. Blackboard merger.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "signal_type": "merger",
        "tags": "higher-ed,suite,merger"
    },
    {
        "name": "EAB",
        "industry": "EdTech / Consulting",
        "segment": "edtech",
        "org_type": "Enterprise",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "Washington, DC",
        "similar_to": "Gray Decision Intelligence",
        "match_tier": 2,
        "match_reason": "Higher ed consulting + tech. DC-based. Advisory + platforms.",
        "fit_score": 78,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "consulting,higher-ed,dc"
    },
    {
        "name": "Rethink First",
        "industry": "EdTech / Healthcare",
        "segment": "edtech",
        "org_type": "SaaS",
        "size_range": "100-200",
        "geography": "National",
        "similar_to": "Lexia, Judge Baker",
        "match_tier": 2,
        "match_reason": "Special education + behavioral health tech. K-12 focus.",
        "fit_score": 75,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 250000,
        "tags": "special-ed,behavioral-health,k12"
    },

    # Tier 2: Behavioral Health
    {
        "name": "LifeStance Health",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "5000-10000",
        "geography": "National",
        "headquarters": "Scottsdale, AZ",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "Largest outpatient mental health. Public company (LFST). Multi-state.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "outpatient,public-company,multi-state,large"
    },
    {
        "name": "Acadia Healthcare",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "10000+",
        "geography": "National",
        "headquarters": "Franklin, TN",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "$3B+ revenue. Behavioral health facilities. PE history.",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "inpatient,large,public"
    },
    {
        "name": "Pinnacle Treatment Centers",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "1000-2000",
        "geography": "National",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "KKR-backed. Addiction treatment. Multi-state expansion.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "signal_type": "acquisition",
        "signal_detail": "KKR acquisition",
        "tags": "addiction,pe-backed,growth"
    },
    {
        "name": "Mountainside Treatment Center",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "200-500",
        "geography": "Regional",
        "headquarters": "Canaan, CT",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "Bain Capital-backed. Northeast focus. Addiction + mental health.",
        "fit_score": 75,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "signal_type": "investment",
        "signal_detail": "Bain Capital investment",
        "tags": "addiction,pe-backed,northeast"
    },
    {
        "name": "Aware Recovery Care",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "200-500",
        "geography": "Regional",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "TPG-backed. Home-based addiction treatment. Innovative model.",
        "fit_score": 77,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 300000,
        "signal_type": "investment",
        "signal_detail": "TPG investment",
        "tags": "addiction,pe-backed,home-based,innovative"
    },
    {
        "name": "Newport Healthcare",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "1000-2000",
        "geography": "National",
        "similar_to": "Lightfully Health, Judge Baker",
        "match_tier": 2,
        "match_reason": "Teen mental health. PE-backed. Residential treatment.",
        "fit_score": 82,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "teen,pe-backed,residential"
    },
    {
        "name": "Discovery Behavioral Health",
        "industry": "Behavioral Health",
        "segment": "behavioral-health",
        "org_type": "Healthcare Provider",
        "size_range": "1000-2000",
        "geography": "National",
        "similar_to": "Lightfully Health",
        "match_tier": 2,
        "match_reason": "Eating disorders + mental health. Multi-state.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "eating-disorders,multi-state"
    },

    # Tier 2: Energy / Utilities
    {
        "name": "National Grid",
        "industry": "Energy / Utilities",
        "segment": "energy",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 29000,
        "geography": "Regional",
        "headquarters": "Waltham, MA",
        "similar_to": "Enel",
        "match_tier": 2,
        "match_reason": "US + UK. Gas + electric. Major digital CX investment.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 800000,
        "tags": "utility,digital-transformation,new-england"
    },
    {
        "name": "Avangrid",
        "industry": "Energy / Utilities",
        "segment": "energy",
        "org_type": "Enterprise",
        "size_range": "5000-10000",
        "employee_count": 7000,
        "geography": "Regional",
        "headquarters": "Orange, CT",
        "similar_to": "Enel, Vicinity",
        "match_tier": 2,
        "match_reason": "Iberdrola subsidiary. Northeast utilities. Clean energy focus.",
        "fit_score": 80,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "utility,clean-energy,northeast"
    },
    {
        "name": "PSEG",
        "industry": "Energy / Utilities",
        "segment": "energy",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 12000,
        "geography": "Regional",
        "headquarters": "Newark, NJ",
        "similar_to": "Enel",
        "match_tier": 2,
        "match_reason": "New Jersey. Clean energy transition. Customer experience focus.",
        "fit_score": 78,
        "budget_estimate": "enterprise",
        "budget_low": 250000,
        "budget_high": 600000,
        "tags": "utility,clean-energy,new-jersey"
    },
    {
        "name": "Eversource",
        "industry": "Energy / Utilities",
        "segment": "energy",
        "org_type": "Enterprise",
        "size_range": "10000+",
        "employee_count": 9500,
        "geography": "Regional",
        "headquarters": "Hartford, CT",
        "similar_to": "Vicinity, Enel",
        "match_tier": 2,
        "match_reason": "New England's largest utility. CT, MA, NH. Clean energy.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "utility,clean-energy,new-england,largest"
    },
    {
        "name": "Green Mountain Power",
        "industry": "Energy / Utilities",
        "segment": "energy",
        "org_type": "Utility",
        "size_range": "500-1000",
        "geography": "Regional",
        "headquarters": "Colchester, VT",
        "similar_to": "Vicinity, Citizens Energy",
        "match_tier": 2,
        "match_reason": "Vermont. B-Corp certified utility. Sustainability leader.",
        "fit_score": 75,
        "budget_estimate": "mid-market",
        "budget_low": 100000,
        "budget_high": 250000,
        "tags": "utility,b-corp,sustainability,vermont"
    },
    {
        "name": "Engie North America",
        "industry": "Energy",
        "segment": "energy",
        "org_type": "Enterprise",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "Houston, TX",
        "similar_to": "Vicinity Energy",
        "match_tier": 2,
        "match_reason": "District energy + renewables. B2B + municipal.",
        "fit_score": 78,
        "budget_estimate": "enterprise",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "district-energy,renewables,b2b"
    },

    # Tier 2: B2B SaaS / MarTech
    {
        "name": "Klaviyo",
        "industry": "MarTech",
        "segment": "saas",
        "org_type": "Enterprise SaaS",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "Boston, MA",
        "similar_to": "RollWorks",
        "match_tier": 2,
        "match_reason": "Boston. $9B+ valuation. B2C CRM/marketing automation. NYSE listed.",
        "fit_score": 85,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "marketing-automation,boston,public,large"
    },
    {
        "name": "6sense",
        "industry": "MarTech / ABM",
        "segment": "saas",
        "org_type": "Growth Stage SaaS",
        "size_range": "500-1000",
        "geography": "National",
        "headquarters": "San Francisco, CA",
        "similar_to": "RollWorks",
        "match_tier": 2,
        "match_reason": "ABM/intent platform. $2B+ valuation. Competitive with RollWorks.",
        "fit_score": 80,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "abm,intent-data,high-growth"
    },
    {
        "name": "Demandbase",
        "industry": "MarTech / ABM",
        "segment": "saas",
        "org_type": "Enterprise SaaS",
        "size_range": "500-1000",
        "geography": "National",
        "headquarters": "San Francisco, CA",
        "similar_to": "RollWorks",
        "match_tier": 2,
        "match_reason": "ABM pioneer. B2B marketing platform.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 150000,
        "budget_high": 400000,
        "tags": "abm,b2b-marketing"
    },
    {
        "name": "ZoomInfo",
        "industry": "MarTech / Data",
        "segment": "saas",
        "org_type": "Enterprise SaaS",
        "size_range": "2000-5000",
        "geography": "National",
        "headquarters": "Vancouver, WA",
        "similar_to": "RollWorks, Gray",
        "match_tier": 2,
        "match_reason": "B2B data + intelligence. $10B+ market cap. Public (ZI).",
        "fit_score": 82,
        "budget_estimate": "enterprise",
        "budget_low": 300000,
        "budget_high": 700000,
        "tags": "data,intelligence,public,large"
    },
    {
        "name": "Seismic",
        "industry": "MarTech / Sales Enablement",
        "segment": "saas",
        "org_type": "Enterprise SaaS",
        "size_range": "1000-2000",
        "geography": "National",
        "headquarters": "San Diego, CA",
        "similar_to": "RollWorks",
        "match_tier": 2,
        "match_reason": "Sales enablement. Boston office. B2B enterprise.",
        "fit_score": 78,
        "budget_estimate": "mid-market",
        "budget_low": 200000,
        "budget_high": 500000,
        "tags": "sales-enablement,b2b"
    },
]

def seed_database():
    """Insert prospect data into the database."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # Insert standard tags
    tags = [
        ("hot-prospect", "red"),
        ("high-priority", "red"),
        ("series-b", "green"),
        ("pe-backed", "purple"),
        ("bcbs", "blue"),
        ("ivy-league", "gold"),
        ("new-england", "teal"),
        ("merger", "orange"),
        ("funding", "green"),
        ("digital-transformation", "cyan"),
    ]

    for tag_name, color in tags:
        cursor.execute(
            "INSERT OR IGNORE INTO tags (name, color) VALUES (?, ?)",
            (tag_name, color)
        )

    # Insert prospects
    for prospect in PROSPECTS:
        cursor.execute("""
            INSERT OR REPLACE INTO companies (
                name, industry, segment, org_type, size_range, employee_count,
                geography, headquarters, similar_to, match_tier, match_reason,
                fit_score, budget_estimate, budget_low, budget_high,
                funding_stage, funding_amount, signal_type, signal_detail, tags
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (
            prospect.get("name"),
            prospect.get("industry"),
            prospect.get("segment"),
            prospect.get("org_type"),
            prospect.get("size_range"),
            prospect.get("employee_count"),
            prospect.get("geography"),
            prospect.get("headquarters"),
            prospect.get("similar_to"),
            prospect.get("match_tier", 2),
            prospect.get("match_reason"),
            prospect.get("fit_score", 50),
            prospect.get("budget_estimate"),
            prospect.get("budget_low"),
            prospect.get("budget_high"),
            prospect.get("funding_stage"),
            prospect.get("funding_amount"),
            prospect.get("signal_type"),
            prospect.get("signal_detail"),
            prospect.get("tags"),
        ))

    conn.commit()

    # Print summary
    cursor.execute("SELECT COUNT(*) FROM companies")
    count = cursor.fetchone()[0]
    print(f"Seeded {count} prospects into database")

    cursor.execute("SELECT segment, COUNT(*) FROM companies GROUP BY segment ORDER BY COUNT(*) DESC")
    print("\nBy segment:")
    for row in cursor.fetchall():
        print(f"  {row[0]}: {row[1]}")

    conn.close()

if __name__ == "__main__":
    seed_database()
